lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "Les semeurs de la Baie - Association de citoyens Pouldreuzic"
      description: >
        Les semeurs de la Baie rassemble des bénévoles désireux de "faire notre part"
        et d'aider notre territoire à avancer sur le chemin de la transition écologique,
        économique et sociale.
